[package]
name = "cargo-psvita"
version = "0.1.0"
edition = "2018"

[dependencies]
cargo_metadata = "0.13.1"
structopt = "0.3.21"

[build-dependencies]
serde = { version="1.0.126", features=["derive"] }
serde_json = "1.0.64"
