[workspace]
members = [
    "cargo-psvita",
    "psvita-linker",
    "psvita-linker/ld-compat-args",
    "psvita-linker/ld-version-script",
    "psvita-linker/compat-args",
    "psvita_sce_types",
]
exclude = ["examples"]
