[config]
default_to_workspace = false

[env]
PROJECT_NAME = "min_sized_vita"
BASE_OUT_DIR = "target/armv7a-sony-psvita"
TARGET_NAME = "armv7a-sony-psvita"

[env.development]
OUT_DIR = "${BASE_OUT_DIR}/debug"
CARGO_BUILD_PROFILE = "dev"

[env.production]
OUT_DIR = "${BASE_OUT_DIR}/release"
CARGO_BUILD_PROFILE = "release"


[tasks.default]
alias = "vita-pack-vpk"

[tasks.update-target]
command = "deno"
args = [
    "eval",
    """
    const targetName = '${TARGET_NAME}';
    const target = JSON.parse(await Deno.readTextFile(targetName + '.no-link-script.json'));
    target['link-script'] = await Deno.readTextFile(targetName + '.ld');
    await Deno.writeTextFile(targetName + '.json', JSON.stringify(target));
    """,
]

[tasks.build]
command = "cargo"
args = [
    "build",
    "--target",
    "${TARGET_NAME}.json",
    "-Zbuild-std=core",
    "-Zunstable-options",
    "--profile",
    "${CARGO_BUILD_PROFILE}",
]
dependencies = ["update-target"]

[tasks.vita-elf-create]
command = "vita-elf-create"
args = ["${OUT_DIR}/${PROJECT_NAME}.elf", "${OUT_DIR}/${PROJECT_NAME}.velf"]
dependencies = ["build"]

[tasks.vita-make-fself]
command = "vita-make-fself"
args = [
    "-s",
    "${OUT_DIR}/${PROJECT_NAME}.velf",
    "${OUT_DIR}/${PROJECT_NAME}.eboot.bin",
]
dependencies = ["vita-elf-create"]

[tasks.vita-mksfoex]
command = "vita-mksfoex"
args = ["ZTNM0002", "${OUT_DIR}/${PROJECT_NAME}.sfo"]

[tasks.vita-pack-vpk]
command = "vita-pack-vpk"
args = [
    "-s",
    "${OUT_DIR}/${PROJECT_NAME}.sfo",
    "-b",
    "${OUT_DIR}/${PROJECT_NAME}.eboot.bin",
    "${OUT_DIR}/${PROJECT_NAME}.vpk",
]
dependencies = ["vita-mksfoex", "vita-make-fself"]
