[package]
name = "psvita-sce-types"
version = "0.1.0"
edition = "2018"

[dependencies]
sha-1 = { version = "0.9.7", optional = true }
bitflags = "1.3.2"
bitfield = "0.13.2"
thiserror = "1.0.30"
arrayvec = "0.7.2"
faerie = "0.16.0"
target-lexicon = "0.11"

[features]
nid-gen = ["sha-1"]
