[package]
name = "psvita-sce-types"
version = "0.1.0"
edition = "2018"

[dependencies]
sha-1 = { version = "0.9.7", optional = true }
bytemuck = { version = "1.7.2", features = ["derive"] }
bitflags = "1.3.2"

[features]
nid-generation = ["sha-1"]
